In [4]:
import pandas as pd

In [5]:
refseq = pd.read_csv('assembly_summary.txt',sep='\t',skiprows=1)

/var/folders/65/rjhnld5s4xv_rsh25jvbsq5r0000gp/T/ipykernel_11917/1503995693.py:1: DtypeWarning: Columns (34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  refseq = pd.read_csv('assembly_summary.txt',sep='\t',skiprows=1)

In [12]:
patric = pd.read_csv('genome_metadata',sep='\t')
patric

/var/folders/65/rjhnld5s4xv_rsh25jvbsq5r0000gp/T/ipykernel_11917/2212897788.py:1: DtypeWarning: Columns (2,6,7,8,9,10,11,12,14,19,20,22,23,24,34,36,37,40,41,42,43,44,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65) have mixed types. Specify dtype option on import or set low_memory=False.
  patric = pd.read_csv('genome_metadata',sep='\t')

,genome_id,genome_name,organism_name,taxon_id,genome_status,strain,serovar,biovar,pathovar,mlst,...,motility,sporulation,temperature_range,optimal_temperature,salinity,oxygen_requirement,habitat,disease,comments,additional_metadata
0,469009.4,"""'Brassica napus' phytoplasma strain TW1""",NaN,469009,WGS,TW1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequence of a strain of bacteria that c...,sample_type:metagenomic assembly;collected_by:...
1,1309411.5,"""'Deinococcus soli' Cha et al. 2014 strain N5""",NaN,1309411,Complete,N5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Genome sequencing of a Gamma-Radiation-Resista...,sample_type:bacterial
2,1123738.3,"""'Echinacea purpurea' witches'-broom phytoplas...",NaN,1123738,WGS,NCHU2014,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,'Echinacea purpurea' witches'-broom phytoplasm...,lab_host:Catharanthus roseus
3,551115.6,"""'Nostoc azollae' 0708""",'Nostoc azollae' 0708,551115,Complete,708,NaN,NaN,NaN,NaN,...,Yes,NaN,Mesophilic,-,NaN,Aerobic,Multiple,NaN,"Nostoc azollae 0708. Nostoc azollae 0708, also...",NaN
4,1856298.3,"""'Osedax' symbiont bacterium Rs2_46_30_T18 str...",NaN,1856298,WGS,Rs2_46_30_T18,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"In this study, we simulate the Deepwater Horiz...",sample_type:metagenomic assembly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059041,1131286.3,zeta proteobacterium SCGC AB-137-J06,zeta proteobacterium SCGC AB-137-J06,1131286,WGS,SCGC AB-137-J06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059042,1131287.3,zeta proteobacterium SCGC AB-602-C20,zeta proteobacterium SCGC AB-602-C20,1131287,WGS,SCGC AB-602-C20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059043,1131288.3,zeta proteobacterium SCGC AB-602-E04,zeta proteobacterium SCGC AB-602-E04,1131288,WGS,SCGC AB-602-E04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059044,1131289.3,zeta proteobacterium SCGC AB-604-B04,zeta proteobacterium SCGC AB-604-B04,1131289,WGS,SCGC AB-604-B04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN
1059045,1131290.3,zeta proteobacterium SCGC AB-604-O16,zeta proteobacterium SCGC AB-604-O16,1131290,WGS,SCGC AB-604-O16,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Single cell genome sequencing of biomineralizi...,NaN

In [28]:
l = pd.read_csv('/Users/gboldirev1/1contig/output_file.csv',dtype=str)
l

,col1,col2,col3,col4,col5,col6,col7,query_fna,subject_fna,query_length,...,n_of_-1,n_of_0,n_of_1,n_of_2,n_of_3,n_of_4,n_of_5,n_of_6,n_of_7,binary_filename
0,25,1001534,TI0902,1001534.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001534.3.fna,GCF_000248435.2_ASM24843v2_genomic.fna,1892744,...,20,312,1868316,0,25,53,24129,0,0,1001534_subject_array_1739113446.bin
1,26,1001542,TIGB03,1001542.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001542.3.fna,GCF_000248415.2_ASM24841v2_genomic.fna,1968651,...,16,0,1968488,0,23,52,29,0,0,1001542_subject_array_1739113448.bin
2,29,1001585,NK-01,1001585.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1001585.3.fna,GCF_000204295.1_ASM20429v1_genomic.fna,5434353,...,0,0,5434353,0,0,0,0,0,0,1001585_subject_array_1739113452.bin
3,92,100226,CFB_NBC_0001,100226.137,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,100226.137.fna,GCF_008931305.1_ASM893130v1_genomic.fna,8667664,...,0,0,8667664,0,0,0,0,0,0,100226_subject_array_1739113458.bin
4,103,1002672,IMCC9063,1002672.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,1002672.3.fna,GCF_000195085.1_ASM19508v1_genomic.fna,1284727,...,0,0,1284727,0,0,0,0,0,0,1002672_subject_array_1739113459.bin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20646,294973,99822,DB60705-15,99822.28,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.28.fna,GCF_009650275.1_ASM965027v1_genomic.fna,2190656,...,0,99,2190557,0,0,0,0,0,0,99822_subject_array_1739184665.bin
20647,294975,99822,NCTC4669,99822.25,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/9...,1,99822.25.fna,GCF_900635345.1_41686_B01_genomic.fna,2201894,...,0,0,2201894,0,0,0,0,0,0,99822_subject_array_1739184667.bin
20648,294989,99822,STREP97-15,99822.29,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,99822.29.fna,GCF_009650295.1_ASM965029v1_genomic.fna,2432570,...,0,99,2432471,0,0,0,0,0,0,99822_subject_array_1739184669.bin
20649,294996,999183,DSM 25104,999183.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999183.3.fna,GCF_029625435.1_ASM2962543v1_genomic.fna,1873758,...,0,0,1873758,0,0,0,0,0,0,999183_subject_array_1739184670.bin
20650,295050,999891,TA208,999891.3,1,https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/0...,1,999891.3.fna,GCF_000195515.1_ASM19551v1_genomic.fna,3937511,...,0,0,3937511,0,0,0,0,0,0,999891_subject_array_1739184673.bin

In [34]:
# Convert 'col4' to string in both dataframes
# Convert 'col4' to string in l and 'genome_id' to string in patric
l['col4'] = l['col4'].astype(str)
patric['genome_id'] = patric['genome_id'].astype(str)

# Now merge the dataframes using the correct column names
result = pd.merge(l, patric, left_on='col4', right_on='genome_id', how='inner')

# View the result
result['genome_status'].value_counts()

genome_status
Complete      17084
WGS            1282
Deprecated     1178
Plasmid           2
Name: count, dtype: int64

In [32]:
# Convert 'ftp_path' and 'col6' to string (if needed) for consistent types
l['col6'] = l['col6'].astype(str)
refseq['ftp_path'] = refseq['ftp_path'].astype(str)

# Now merge the dataframes on 'col6' in l and 'ftp_path' in refseq
result1 = pd.merge(l, refseq, left_on='col6', right_on='ftp_path', how='inner')

# View the result
result1['assembly_level'].value_counts()

assembly_level
Complete Genome    17047
Chromosome          2637
Contig               921
Scaffold              46
Name: count, dtype: int64